# Generated by Django 2.2.7 on 2021-04-22 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_hire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='time_start',
        ),
        migrations.AddField(
            model_name='hire',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hire',
            name='event',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hire',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=500)),
                ('prep_time', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Chef')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Chef')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Customer')),
            ],
        ),
    ]
