# Generated by Django 2.2.7 on 2021-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210422_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
