# Generated by Django 2.2.7 on 2021-04-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210423_0106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hire',
            new_name='Booking',
        ),
    ]
