# Generated by Django 2.2.7 on 2021-04-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210423_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
