# Generated by Django 2.2.7 on 2021-04-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='email_address',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
